#ifndef _MORSE_TYPES_H_
#define _MORSE_TYPES_H_

enum morse_config_test_mode {
    MORSE_CONFIG_TEST_MODE_DISABLED,
    MORSE_CONFIG_TEST_MODE_DOWNLOAD_ONLY,
    MORSE_CONFIG_TEST_MODE_DOWNLOAD_AND_GET_HOST_TBL_PTR,
    MORSE_CONFIG_TEST_MODE_GET_HOST_TBL_PTR_ONLY,
    MORSE_CONFIG_TEST_MODE_RESET,
    MORSE_CONFIG_TEST_MODE_BUS,
    MORSE_CONFIG_TEST_MODE_BUS_PROFILE,
    MORSE_CONFIG_TEST_MODE_INVALID,
};

#endif /* _MORSE_TYPES_H_ */
